# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: 14islands.com
# this is necessary for jekyll + gh-pages
# see here: http://jekyllrb.com/docs/github-pages/
baseurl: /14islands-com
description: 14islands is a web development studio that cares deeply about creating great user experiences.
keywords: "Web Development, Web Design, UX, Web Developers, Digital, Studio, Agency, Stockholm, Consulting, Training, HTML, CSS, JavaScript, WordPress"
og_type: website
og_image: "/images/about/we-love-what-we-do.jpg"
encoding: utf-8
locale: en_US
author:
  name: 14islands
  email: hello@14islands.com

# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: ['.htaccess']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: false
hide_private: false

permalink: pretty
paginate: 1
paginate_path: 'page:num'

# Markdown library
markdown: redcarpet
#   extensions: ['fenced_code_blocks', 'smart']

highlighter: pygments
