backend:
  name: github
  repo: 14islands/14islands-com # Path to your Github repository
  branch: feature/netlifycms # Branch to update

media_folder: "app/images"
public_folder: "/images"


collections:
  - name: "blog" # Used in routes, e.g. /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "app/blog/_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Open Graph Image", name: "og_image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
